### ISSUE TITLE
Filter Feature

### ISSUE THREAD

**Issue by datanotion** [thebakeryio/meteor-ddp-monitor#17]
It would be wonderful to see a **filter** feature implemented.  Sometimes I'm only interested in seeing certain messages, and have to search through the flood to see if it happened.  With a text filter, I could "watch" only certain method calls.

Thanks for such an awesome tool!

**Comment by datanotion** [comment]
Or maybe even an **ignore** filter feature.  I just noticed that most of the "noise" I see are generally only 2 or 3 different calls to the server.

**Comment by callmephilip** [comment]
hey Pat. we've been thinking about the right away of doing filters for some time now. what do you think about the approach that Network panel uses in Chrome devtools?

![filters](https://cloud.githubusercontent.com/assets/492025/11423203/553db49e-943a-11e5-8285-228201d0bf19.png)

we could have similar UX with message categories (e.g. Subscriptions, Methods etc)

**Comment by datanotion** [comment]
+1  I think that would be an excellent approach!
