### ISSUE TITLE
Give ids links to messages

### ISSUE THREAD

**Issue by HunterNL** [thebakeryio/meteor-ddp-monitor#7]
I'd be really neat if any given ID was given a link which when clicked would scroll to/expand/highlight the message the ID refers to.

**Comment by callmephilip** [comment]
this is supported in 0.6 for result and ready messages
![ddp0 6](https://cloud.githubusercontent.com/assets/492025/11061664/8cdda41e-87a0-11e5-92e9-cf773cbda550.gif)
